name: Deploy to S3

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This uses the latest version that supports Node.js 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # This uses the latest version that supports Node.js 20
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # e.g., us-east-1

      - name: Sync S3 bucket
        run: |
          aws s3 sync . s3://north-inlet/ --exclude ".git/*" --delete
